import { Inter } from 'next/font/google'
import '../fontawesome.js'
import './globals.css'
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet"></link>

      <Head>
            <title>
           
            </title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
